version: '3.7'
# Persist data from Prometheus and Grafana with Docker volumes
volumes:
  prometheus_data: {}
  grafana_data: {}

# Connect containers via the front-tier and back-tier network
networks:
  backend:

# Container services
services:
  prometheus:
    # Prometheus uses the latest image
    image: prom/prometheus:latest

    # Stores Prometheus data locally in the prometheus directory
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

    # Setup commands for Prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      #- '--web.listen-address=127.0.0.1:9090'

    # Exposes port 9090 to access Prometheus web UI
    ports:
      - 9090:9090
    #network_mode: "host"

    # Connects Prometheus service to the back-tier network
    networks:
      - backend

    # Restart policy for Prometheus service set to always
    restart: always

  grafana:
    # Grafana uses the latest image
    image: grafana/grafana:latest

    # Sets user ID to 472
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/grafana.config
    networks:
      - backend
    #network_mode: "host"
    restart: always
